import type { GroupedRepoData } from "../types/repo"
import json from "./repos.json"

/**
 * Generated by `bun run fetch-repos`. JSON imports widen string literals such
 * as `type: "app"` to `string`, so the shape is asserted here once instead of
 * in every page that reads it.
 */
export const reposData = json as unknown as GroupedRepoData
